name: barcode update

on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  testsuite:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: update
        shell: bash -l {0}
        run: |
          conda activate test
          wget https://raw.githubusercontent.com/andersen-lab/Freyja/main/freyja/data/usher_barcodes.csv
          wget https://raw.githubusercontent.com/andersen-lab/Freyja/main/freyja/data/curated_lineages.json
      - name: update history if output is different 
        run: |
          echo "running git diff, committing if different"
          if [[($(git status usher_barcodes.csv --porcelain | wc -c) -ne 0)]]; then
            echo "changes were made, updating barcodes"
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            cp usher_barcodes.csv history_barcodes/usher_barcodes$(date +"%m_%d_%Y-%H-%M").csv
            cp curated_lineages.json history_metadata/curated_lineages$(date +"%m_%d_%Y-%H-%M").json
            git add usher_barcodes.csv
            git add curated_lineages.json
            git add history_barcodes/usher_barcodes$(date +"%m_%d_%Y-%H-%M").csv
            git add history_metadata/curated_lineages$(date +"%m_%d_%Y-%H-%M").json
            git commit -m "updating historic data"
            git push origin main
          else
              echo "no changes were made, doing nothing."
          fi; 
